server:
  port: 8088

spring:
  application:
    name: notification-service
  r2dbc:
    url: r2dbc:postgresql://sonifoy-db:5432/notification_db
    username: sonifoy_user
    password: sonifoy_password
  kafka:
    bootstrap-servers: sonifoy-kafka:29092
    consumer:
      group-id: notification-service-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      properties:
        '[spring.deserializer.value.delegate.class]': org.springframework.kafka.support.serializer.JsonDeserializer
        '[spring.json.trusted.packages]': "*"

eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery-service:8761/eureka/
